spring:
  application:
    name: gateway-redis
  cloud:
    gateway:
      redis-route-definition-repository:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8082

